import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
/**
 * Metadata default for the page.
*/
export const metadata: Metadata = {
    title: 'Sobat Sehat',
    description: 'Generated by Sobat Sehat app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode,
}) {
    return (
        <html lang='en'>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}
